#!/usr/bin/python -W ignore
# -*- coding: utf-8 -*-

# A munin plugin for visualizing the status of Twitter-enabled dehumidifiers.

# Name as follows:
# /etc/munin/plugins/dehumid_<dehumidifiername>
# where <dehumidifiername> is the name of the dehumidifier.

# Currently supports:
#   mwwdehumid http://github.com/mwalling/arduino-twitdehumid/tree

# Returns 0 for an empty dehumidifier, 100 for a full dehumidifier.
# In the future, may return a percentage, if anyone ever goes insane and
# does that.  (e.g. 0.5 would be half-full)

# Ryan Tucker <rtucker@gmail.com> 2009/06/25

import os
import re
import sys
import twitter

# Full and empty regexps for various dehumidifiers
dehumidifiers = {'mwwdehumid':
                    {'full': 'My tank is full.*',
                     'empty': 'Thanks for emptying me.*'}
                }

myname = os.path.split(sys.argv[0])[-1].split('_')[1]

def print_config(user, name):
	# outputs the configuration for a given instance
	print """graph_title Status for %s
graph_args --base 1000 --lower-limit 0
graph_vlabel Fullness (percent)
graph_category Climate
graph_info Fullness of the dehumidifier
%s.label Percent full
%s.draw AREA""" % (user.name, name, name)

def get_fullness_via_twitter(user, name):
    # returns the percent full from twitter
    text = user.status.text
    # Is it full?
    rg = re.compile(dehumidifiers[name]['full'])
    if rg.match(text):
        return 100
    # Is it empty?
    rg = rg.compile(dehumidifiers[name]['empty'])
    if rg.match(text):
        return 0
    # Is it... indeterminent?
    return 50

def main():
    api = twitter.Api()
    user = api.GetUser(myname)
    if len(sys.argv) > 1 and sys.argv[1] == 'config':
        print_config(user, myname)
    else:
        fullness = get_fullness_via_twitter(user, myname)
        print '%s.value %i' % (myname, fullness)

if __name__ == '__main__':
	main()

